language: python

python:
    - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install requests
    - pip install Flask
    - pip install Flask-Script
    - pip install Flask-SQLAlchemy
    - pip install flask-restful
    - pip install PyMySQL

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - python3 tests.py

notifications:
  slack: swesquad:KbXXWvyvnkk2Jh7IkxxettzX