FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ildb

The ILDB - the Internet Legislative Database - is an API that allows users 
to pull specific legislators, all present congressmen and senators, 
specific bills or all bills.

## Legislator Collection [/api/legislators{?limit}]
Calling with no limit argument returns all legislators in the databse.

### List all legislators [GET]

+ Parameters
    + limit (number) - optional argument specifying the number of legislators to retrieve

+ Response 200 (application/json)

        [
            {
                "birthday": "1947-01-23",
                "description": "Senior Senator from Delaware",
                "firstname": "Thomas",
                "id": 300019,
                "lastname": "Carper",
                "party": "Democrat",
                "photo_link": "https://www.govtrack.us/data/photos/300019-200px.jpeg",
                "start_date": "2013-01-03",
                "state": "DE",
                "title": "Senator",
                "twitter": "SenatorCarper",
                "website": "http://www.carper.senate.gov",
                "youtube": "senatorcarper"
            },
            {
                "birthday": "1937-12-07",
                "description": "Senior Senator from Mississippi",
                "firstname": "Thad",
                "id": 300023,
                "lastname": "Cochran",
                "party": "Republican",
                "photo_link": "https://www.govtrack.us/data/photos/300023-200px.jpeg",
                "start_date": "2015-01-06",
                "state": "MS",
                "title": "Senator",
                "twitter": "SenThadCochran",
                "website": "http://www.cochran.senate.gov",
                "youtube": "sencochran"
            },
            {
                "birthday": "1952-12-07",
                "description": "Senior Senator from Maine",
                "firstname": "Susan",
                "id": 300025,
                "lastname": "Collins",
                "party": "Republican",
                "photo_link": "https://www.govtrack.us/data/photos/300025-200px.jpeg",
                "start_date": "2015-01-06",
                "state": "ME",
                "title": "Senator",
                "twitter": "SenatorCollins",
                "website": "http://www.collins.senate.gov",
                "youtube": "SenatorSusanCollins"
            }
        ]

## Single legislator [/api/legislators/{legislator_id}]

+ Parameters
    + legislator_id (number) - ID of the legislator

### Get one legislator [GET]
Use the legislator id listed in the legislators table to retrieve that specific person.
+ Response 200 (application/json)

        {
            "birthday": "1940-11-11",
            "description": "Junior Senator from California",
            "firstname": "Barbara",
            "id": 300011,
            "lastname": "Boxer",
            "party": "Democrat",
            "photo_link": "https://www.govtrack.us/data/photos/300011-200px.jpeg",
            "start_date": "2011-01-05",
            "state": "CA",
            "title": "Senator",
            "twitter": "SenatorBoxer",
            "website": "http://www.boxer.senate.gov",
            "youtube": "SenatorBoxer"
        }

## Bills Collection [/api/bills{?limit}]
Calling with no limit argument will return all the bills in the database.

+ Parameters
    + limit (number) - optional argument specifying the number of bills to retrieve

### List all bills [GET]

+ Response 200 (application/json)

        [
            {
                "bill_type": "house_bill",
                "current_status": "referred",
                "date": "2010-07-01",
                "id": 4,
                "name": "One Global Internet Act of 2010"
            },
            {
                "bill_type": "house_bill",
                "current_status": "referred",
                "date": "2009-01-09",
                "id": 6,
                "name": "Prevention Through Affordable Access Act of 2009"
            },
            {
                "bill_type": "house_resolution",
                "current_status": "reported",
                "date": "2009-05-21",
                "id": 7,
                "name": "Directing the Secretary of Defense to transmit to the House of Representatives the fiscal year 2010 30-year shipbuilding plan relating to the long-term shipbuilding strategy of the Department of Defense, as required by section 231 of title 10, United Stat"
            }
        ]

## Single Bill [/api/bills/{bill_id}]
Use the bill id listed in the bills table to retrieve that specific bill.

+ Parameters
    + bill_id (number) - ID of the bill

### Get one bill [GET]

+ Response 200 (application/json)

        {
            "bill_type": "house_bill",
            "current_status": "referred",
            "date": "2010-07-01",
            "id": 4,
            "name": "One Global Internet Act of 2010"
        }